In [1]:
import torch

In [2]:
x = torch.randn(4,requires_grad=True)

How a simple optimization works

* foward : calculates Y
* gets grad
* backwards: updates the parameters using the grad

In [3]:
# lets say we want to train the model : y = 3*x + 2

y = 3*x + 2
print(y)
z = y*y*2
z = z.mean()
print(z)


tensor([3.1558, 3.3833, 2.6902, 2.5759], grad_fn=<AddBackward0>)
tensor(17.6391, grad_fn=<MeanBackward0>)


In [4]:
z.backward()

In [6]:
x.grad

tensor([ 9.4673, 10.1499,  8.0706,  7.7278])

In [7]:
x

tensor([0.3853, 0.4611, 0.2301, 0.1920], requires_grad=True)

O backward stores the derivative value, so we most empty the tensor before a new optimization

In [12]:
# para 
weights = torch.ones(3, requires_grad = True)

for i in range(3):
    
    y = (weights*3 + 1).sum()
    z = y.mean()
    
    z.backward()
    print(weights.grad)

tensor([3., 3., 3.])
tensor([6., 6., 6.])
tensor([9., 9., 9.])


In [14]:
weights.grad.zero_()

tensor([0., 0., 0.])

In [15]:
print(weights.grad)

tensor([0., 0., 0.])
