# Lesson 1 on pytorch for deeplearning
### tensor basics
- zeros,ones,rand,empty
- operacoes com tensores (add, multiplicar, sub,div)
- view
- transform in numpy
- every function with _ changes data inplace
- checking if cuda is available
- setting device to #azureml-core of version 1.0.72 or higher is required
- nao da pra transformar um atensor gpu em numpy

In [2]:
import torch

In [8]:
print(torch.zeros(3,3))
print(' ')
print(torch.ones(3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [10]:
print(torch.empty(2,2,2))
print(' ')
print(torch.rand([3,3]))

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
 
tensor([[0.0873, 0.2254, 0.1190],
        [0.0255, 0.6409, 0.4183],
        [0.4711, 0.4724, 0.9790]])


In [14]:
x = torch.ones([2,1])
y = torch.ones([1,2])

print(x)
print('')
print(x + y)

tensor([[1.],
        [1.]])

tensor([[2., 2.],
        [2., 2.]])


In [19]:
torch.gpu

AttributeError: 'Tensor' object has no attribute 'to_numpy'