# Lesson 1 on pytorch for deeplearning
### tensor basics
- zeros,ones,rand,empty
- operacoes com tensores (add, multiplicar, sub,div)
- view
- transform in numpy
- every function with _ changes data inplace
- checking if cuda is available
- setting device to #azureml-core of version 1.0.72 or higher is required
- nao da pra transformar um atensor gpu em numpy

In [2]:
import torch

In [18]:
print(torch.zeros(3,3))
print(' ')
print(torch.ones(3,3))
print(' ')
print(torch.ones(3,3).size())

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
 
torch.Size([3, 3])


In [4]:
print(torch.empty(2,2,2))
print(' ')
print(torch.rand([3,3]))

tensor([[[7.6094e+19, 1.9772e-42],
         [0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]]])
 
tensor([[0.1656, 0.2290, 0.7049],
        [0.1973, 0.1754, 0.6171],
        [0.6258, 0.9490, 0.4449]])


## operations with tensors

In [30]:
x = torch.ones([2,1])
y = torch.ones([1,2])


print(x)
print('')
print(x + y)

tensor([[1.],
        [1.]])

tensor([[2., 2.],
        [2., 2.]])


In [31]:
# when a function has underline at the end, its an inline function
print('x + x with add')
print(x.add(x))
print('heres how x looks like after the sum')
print(x)
print('x + x with add_')
print(x.add_(x))
print('how X looks like, after the sum')
print(x)

x + x with add
tensor([[2.],
        [2.]])
heres how x looks like after the sum
tensor([[1.],
        [1.]])
x + x with add_
tensor([[2.],
        [2.]])
how X looks like, after the sum
tensor([[2.],
        [2.]])


In [14]:
# turn tensor to numpy
print(x.numpy())
print('')
#testing type
print(type(x.numpy()))
print('')
# see tensor as a vector
print(torch.ones([3,3,3]).view(27))
print('')
print(torch.ones([3,3,3]).view(27).type)
print('')
print(type(torch.ones([3,3,3]).view(27)))

[[1.]
 [1.]]

<class 'numpy.ndarray'>

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.])

<built-in method type of Tensor object at 0x00000297F19288B0>

<class 'torch.Tensor'>


How to check if there's gpu available

In [15]:
torch.cuda.is_available()

False

In [32]:
device = torch.device('cuda')
z = torch.ones(5,device=device)

z2 = x + z



In [ ]:
x.to(device)
z2 = x + z
z2 = z2.to('cpu')
z2

tensor -> numpy -> tensor

In [20]:
print(x.numpy())
print('')
#testing type
print(type(x.numpy()))
print('')
print(torch.from_numpy(x.numpy()))
print('')
#testing type
print(type(torch.from_numpy(x.numpy())))


[[1.]
 [1.]]

<class 'numpy.ndarray'>

tensor([[1.],
        [1.]])

<class 'torch.Tensor'>
